name: Codecov Coverage

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests and generate Kover report
        run: ./gradlew :kover:koverXmlReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./kover/build/reports/kover/report.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
